name: Extract version and build number

inputs:
  flavor:
    required: true

outputs:
  build-name:
    value: ${{ steps.name.outputs.BUILD_NAME }}
  build-number:
    value: ${{ steps.number.outputs.BUILD_NUMBER }}

runs:
  using: composite
  steps:
    - name: â¬†ï¸ Extract build name
      id: name
      run: |
        TAG=${GITHUB_REF#refs/*/}
        BUILD_NAME=${TAG%"-${{ inputs.flavor }}"}
        echo "$BUILD_NAME"
        echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_OUTPUT
      shell: bash
    - name: ðŸ”¢ Extract build number
      id: number
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        BUILD_NUMBER=$(($RUN_NUMBER+10000))
        echo "$BUILD_NUMBER"
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_OUTPUT
      shell: bash
