include: package:devartel_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "**/generated/**/*.dart"
    - "**/generated/*.dart"
    - "lib/generated_plugin_registrant.dart"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - always-remove-listener
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        - acceptable-level: 2
    - avoid-returning-widgets
    - avoid-throw-in-catch-block
    - avoid-unused-parameters
    - avoid-unnecessary-setstate
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-expanded-as-spacer
    - avoid-unrelated-type-assertions
    - avoid-wrapping-in-padding
    - avoid-shrink-wrap-in-lists
    - avoid-top-level-members-in-tests
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-magic-number:
        allowed: [ 0, 1, 2, 4, 8, 12, 16, 20, 24, 32, 40, 48 ]
    - prefer-async-await
    - prefer-immediate-return
    - prefer-enums-by-name
    - prefer-last
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - prefer-correct-edge-insets-constructor
    - prefer-correct-identifier-length:
        exceptions: [ 'i', 'x', 'y', 'r', 't' ]
        min-identifier-length: 2
    - prefer-extracting-callbacks:
        allowed-line-count: 2
        ignored-named-arguments:
          - listener
          - transitionBuilder
    - tag-name:
        var-names: [ _tag, _logTag, tag, logTag ]
        strip-prefix: _
    - ban-name:
        entries:
          - ident: RichText
            description: Use Text.rich instead
          - ident: Theme
            description: Use AppTheme instead
    - member-ordering:
        order:
          - constructors
          - public-static-const-fields
          - public-static-fields
          - public-static-methods
          - private-static-const-fields
          - private-static-fields
          - private-static-methods
          - named-constructors
          - factory-constructors
          - overridden-fields
          - public-fields
          - private-fields
          - overridden-getters-setters
          - public-getters-setters
          - private-getters-setters
          - overridden-methods
          - public-methods
          - private-methods
