name: da_project

packages:
  - apps/**
  - packages/**

scripts:
  prepare:
    description: "‍🍳 Prepare the project for hacking"
    failFast: true
    run: |
      melos clean &&
      melos bs &&
      melos gen &&
      melos prepare:ios &&
      melos format &&
      melos fix &&
      melos analyze

  prepare:ios:
    description: "🥜 Prepare iOS: install cocoa pods"
    failFast: true
    concurrency: 1
    packageFilters:
      fileExists: "ios/Podfile"
    exec: |
      cd ios &&
      flutter precache --ios &&
      pod install --repo-update

  gen:loc:
    description: "🎌️ Generate localization"
    failFast: true
    concurrency: 1
    orderDependents: true
    packageFilters:
      fileExists: l10n.yaml
      dependsOn: "flutter_localizations"
    exec: flutter gen-l10n

  gen:prepare:
    description: "🧩 Install dependencies required for codegen"
    failFast: true
    run: |
      dart pub global activate flutter_gen

  gen:code:
    description: "👷 Generate code"
    failFast: true
    concurrency: 1
    orderDependents: true
    packageFilters:
      dependsOn: "build_runner"
    exec: dart run build_runner build --delete-conflicting-outputs

  gen:
    description: "🚧 Generate everything"
    run: |
      melos gen:prepare
      melos gen:code --no-select
      melos gen:loc --no-select

  fix:
    description: "🔧 Fix lint problems"
    failFast: true
    exec: dart fix --apply

  build:android:
    description: "🤖 Build Android app"
    failFast: true
    run: |
      cd apps/app &&
      flutter build ${PACKAGE_FORMAT:-apk} --flavor $FLAVOR --build-number=$BUILD_NUMBER --build-name=$BUILD_NAME

  build:ios:
    description: "🍏 Build iOS app"
    failFast: true
    run: |
      cd apps/app &&
      flutter build ios --flavor $FLAVOR --build-number=$BUILD_NUMBER --build-name=$BUILD_NAME

  storybook:build:
    description: "🧚 Build Storybook for production"
    failFast: true
    run: |
      cd apps/storybook &&
      flutter build web

  storybook:run:
    description: "✨ Run Storybook in browser"
    failFast: true
    run: |
      cd apps/storybook &&
      flutter run -d chrome

  gh:set-secrets:
    description: "🤐 Set GitHub Actions Secrets from ./github/.env"
    failFast: true
    run: |
      cd .github &&
      gh secret set -f .env

command:
  clean:
    hooks:
      post: |
        find . -type f \( -name \*.g.dart -o -name \*.freezed.dart -o -name \*.gen.dart -o -name \*.lock \) -delete && 
        cd apps/app/ios && pod cache clean --all && cd ../../..
