name: da_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: any
  collection: any
  meta: any
  go_router: 10.0.0
  cached_network_image: 3.2.3
  flutter_hooks: 0.18.1
  hooks_riverpod: 2.4.10
  riverpod_annotation: 2.3.4
  ui_kit:
    path: packages/ui_kit
  logger:
    path: packages/logger
  firebase_core: 2.30.1
  firebase_analytics: 10.10.4
  shared_preferences: 2.2.2
  flutter_svg: 2.0.10+1
  flutter_native_splash: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.9
  flutter_gen_runner: 5.4.0

  devartel_analysis:
    git:
      url: https://github.com/DevArtel/devartel_analysis.git
      ref: v3.0.0

  riverpod_generator: 2.3.11
  riverpod_lint: 2.3.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/

flutter_gen:
  output: lib/resources
  line_length: 120

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
