name: da_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.1.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  intl: any
  collection: any
  meta: any
  go_router: 10.0.0
  cached_network_image: 3.2.3
  flutter_hooks: 0.18.1
  hooks_riverpod: 2.4.10
  riverpod_annotation: 2.3.4
  ui_kit:
    path: packages/ui_kit
  logger:
    path: packages/logger
  firebase_core: 2.24.0
  shared_preferences: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.6
  devartel_analysis:
    git:
      url: https://github.com/DevArtel/devartel_analysis.git
      ref: v3.0.0

  riverpod_generator: 2.3.11
  riverpod_lint: 2.3.9

flutter:
  uses-material-design: true
  generate: true
