name: storybook
description: The app storybook
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  widgetbook: 3.2.0
  ui_kit:
    path: ../packages/ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  devartel_analysis:
    git:
      url: https://github.com/DevArtel/devartel_analysis.git
      ref: v2.0.0

flutter:
  uses-material-design: true
