name: logger
description: logger
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: 1.2.0
  logging_appenders: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  devartel_analysis:
    git:
      url: https://github.com/DevArtel/devartel_analysis.git
      ref: v3.0.0
