name: ui_kit
description: UI kit
version: 0.0.1
homepage:

environment:
  sdk: ^3.1.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  devartel_analysis:
    git:
      url: https://github.com/DevArtel/devartel_analysis.git
      ref: v3.0.0

flutter:
  generate: true
  uses-material-design: true
