name: ui_kit
description: UI kit
version: 0.0.1
homepage:

environment:
  sdk: 3.4.1
  flutter: 3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  cached_network_image: ^3.2.3
  flutter_svg: 2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  flutter_gen_runner: 5.4.0
  devartel_analysis:
    git:
      url: https://github.com/DevArtel/devartel_analysis.git
      ref: v3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_gen:
  output: lib/src/resources
  line_length: 120

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
