name: screen_builder
description: A package to help you build screens in a more organized way
version: 1.0.0

environment:
  sdk: ^3.1.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: 0.20.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
