name: storybook
description: The app storybook
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.4.1
  flutter: 3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  widgetbook_annotation: 3.1.0
  widgetbook: 3.7.0
  ui_kit: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  devartel_analysis:
    git:
      url: https://github.com/DevArtel/devartel_analysis.git
      ref: v3.0.0
  widgetbook_generator: 3.7.0
  build_runner: 2.4.9

flutter:
  uses-material-design: true
