name: Create release in Sentry

inputs:
  environment:
    required: true
  version:
    required: true
  build-number:
    required: true
  token:
    required: true

runs:
  using: composite
  steps:
    - uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.token }}
        SENTRY_ORG: yasno-live
        SENTRY_PROJECT: flutter
      with:
        environment: ${{ inputs.environment }}
        version: yasno-mobile.${{ inputs.environment }}@${{ inputs.version }}+${{ inputs.build-number }}
        finalize: true
