default_platform(:android)

platform :android do
  desc "Distribute to Firebase App Distribution"
  lane :deploy_staging do |options|
    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      apk_path: "../build/app/outputs/flutter-apk/app-staging-release.apk",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: options[:changelog],
      groups: "test-team"
    )
  end

  desc "Release to Google Play Alpha"
  lane :deploy_prod do
    upload_to_play_store(
      track: 'alpha',
      release_status: 'draft',
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      changes_not_sent_for_review: true
    )
  end

end
